name: Build Application

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    name: Build macOS App
    runs-on: macos-14
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
        
    - name: Build macOS Application
      id: build
      run: |
        xcodebuild \
          -project LightCommander.xcodeproj \
          -scheme LightCommander \
          -configuration Release \
          clean archive
        
        echo "APPLICATION_PATH=$(xcodebuild -project LightCommander.xcodeproj -scheme LightCommander -configuration Release -showBuildSettings 2>/dev/null | awk '$1 == "BUILD_DIR" {print $3; exit}')"

    - name: Create DMG
      run: |
        echo $ARCHIVE_PATH
        npm i -g create-dmg
        create-dmg ${{ steps.build.outputs.APPLICATION_PATH }}/Release/LightCommander.app

    - name: 'Upload Application Bundle'
      run: gh release upload ${{ github.ref }} LightCommander.dmg
      env:
        GITHUB_TOKEN: ${{ github.TOKEN }}
      shell: bash